### ISSUE TITLE
登録機能作成！！

### ISSUE THREAD

**Issue by MasanoriIwakura** [tako-eng-org/spring-todo#2]
DBの用意
- [ ] sqliteファイルを作成する
- [ ] DBを作成する（ファイル単位の場合はないかも。調査する）
- [ ] テーブル構造を作成する
      - ID（主キー）
      - 内容
      - 登録日
      - 更新日

javaからCRUD（今回は登録）できればゴール

**Comment by MasanoriIwakura** [comment]
今日中！！

**Comment by tako-eng** [comment]
## いまできていること
 - POSTでregisterを呼んで登録すること（固定文字）
## いまできていないこと（TODO）
 - View作成
 - 画面から入力した内容を登録すること
 - 一覧画面に反映表示する（リダイレクトする）一覧画面表示の機能を呼び出す

**Comment by tako-eng** [comment]
登録機能作成完了。
だいぶ時間がかかってしまいました。。
